### ISSUE TITLE
🔬 Tracking issue for ReactiveX operators

### ISSUE THREAD

**Issue by alexanderlinne** [alexanderlinne/rxui#5]
Tracking issue for the implementation status of ReactiveX operators as specified [in the ReactiveX docs](http://reactivex.io/documentation/operators.html).
## Creating Observables
- [x] **create** [[ReactiveX docs](http://reactivex.io/documentation/operators/create.html)]: "create an Observable from scratch by calling observer methods programmatically"
- [ ] **defer** [[ReactiveX docs](http://reactivex.io/documentation/operators/defer.html)]: "do not create the Observable until the observer subscribes, and create a fresh Observable for each observer"
- [ ] **empty/never/throw** [[ReactiveX docs](http://reactivex.io/documentation/operators/empty-never-throw.html)]: "create Observables that have very precise and limited behavior"
- [x] **from** [[ReactiveX docs](http://reactivex.io/documentation/operators/from.html)]: "convert some other object or data structure into an Observable"
[implemented as [into traits](https://github.com/alexanderlinne/rxui/blob/1848a5e07e8f7fded45c6cc3d940358c15e8aa48/rxui_rx/src/core/into.rs)]
- [ ] **interval** [[ReactiveX docs](http://reactivex.io/documentation/operators/interval.html)]: "create an Observable that emits a sequence of integers spaced by a particular time interval"
- [ ] **just** [[ReactiveX docs](http://reactivex.io/documentation/operators/just.html)]: "convert an object or a set of objects into an Observable that emits that or those objects"
- [ ] **range** [[ReactiveX docs](http://reactivex.io/documentation/operators/range.html)]: "create an Observable that emits a range of sequential integers"
- [ ] **repeat** [[ReactiveX docs](http://reactivex.io/documentation/operators/repeat.html)]: "create an Observable that emits a particular item or sequence of items repeatedly"
- [ ] **start** [[ReactiveX docs](http://reactivex.io/documentation/operators/start.html)]: "create an Observable that emits the return value of a function"
- [ ] **timer** [[ReactiveX docs](http://reactivex.io/documentation/operators/timer.html)]: "create an Observable that emits a single item after a given delay"
## Transforming Observables
- [ ] **timer** [[ReactiveX docs](http://reactivex.io/documentation/operators/timer.html)]: "create an Observable that emits a single item after a given delay"
- [ ] **flat_map** [[ReactiveX docs](http://reactivex.io/documentation/operators/flatmap.html)]: "transform the items emitted by an Observable into Observables, then flatten the emissions from those into a single Observable"
- [ ] **group_by** [[ReactiveX docs](http://reactivex.io/documentation/operators/groupby.html)]: "divide an Observable into a set of Observables that each emit a different group of items from the original Observable, organized by key"
- [x] **map** [[ReactiveX docs](http://reactivex.io/documentation/operators/map.html)]: "transform the items emitted by an Observable by applying a function to each item"
- [x] **scan** [[ReactiveX docs](http://reactivex.io/documentation/operators/scan.html)]: "apply a function to each item emitted by an Observable, sequentially, and emit each successive value"
- [ ] **window** [[ReactiveX docs](http://reactivex.io/documentation/operators/window.html)]: "periodically subdivide items from an Observable into Observable windows and emit these windows rather than emitting the items one at a time"
## Filtering Observables
- [ ] **debounce** [[ReactiveX docs](http://reactivex.io/documentation/operators/debounce.html)]: "only emit an item from an Observable if a particular timespan has passed without it emitting another item"
- [ ] **distinct** [[ReactiveX docs](http://reactivex.io/documentation/operators/distinct.html)]: "suppress duplicate items emitted by an Observable"
- [ ] **element_at** [[ReactiveX docs](http://reactivex.io/documentation/operators/elementat.html)]: "emit only item n emitted by an Observable"
- [ ] **filter** [[ReactiveX docs](http://reactivex.io/documentation/operators/filter.html)]: "emit only those items from an Observable that pass a predicate test"
- [ ] **first** [[ReactiveX docs](http://reactivex.io/documentation/operators/first.html)]: "emit only the first item, or the first item that meets a condition, from an Observable"
- [ ] **ignore_elements** [[ReactiveX docs](http://reactivex.io/documentation/operators/ignoreelements.html)]: "do not emit any items from an Observable but mirror its termination notification"
- [ ] **last** [[ReactiveX docs](http://reactivex.io/documentation/operators/last.html)]: "emit only the last item emitted by an Observable"
- [ ] **sample** [[ReactiveX docs](http://reactivex.io/documentation/operators/sample.html)]: "emit the most recent item emitted by an Observable within periodic time intervals"
- [ ] **skip** [[ReactiveX docs](http://reactivex.io/documentation/operators/skip.html)]: "suppress the first n items emitted by an Observable"
- [ ] **skip_last** [[ReactiveX docs](http://reactivex.io/documentation/operators/skiplast.html)]: "suppress the last n items emitted by an Observable"
- [ ] **take** [[ReactiveX docs](http://reactivex.io/documentation/operators/take.html)]: "emit only the first n items emitted by an Observable"
- [ ] **take_last** [[ReactiveX docs](http://reactivex.io/documentation/operators/takelast.html)]: "emit only the last n items emitted by an Observable"
## Combining Observables
- [ ] **take_last** [[ReactiveX docs](http://reactivex.io/documentation/operators/takelast.html)]: "emit only the last n items emitted by an Observable"
- [ ] **combine_latest** [[ReactiveX docs](http://reactivex.io/documentation/operators/combinelatest.html)]: "when an item is emitted by either of two Observables, combine the latest item emitted by each Observable via a specified function and emit items based on the results of this function"
- [ ] **join** [[ReactiveX docs](http://reactivex.io/documentation/operators/join.html)]: "combine items emitted by two Observables whenever an item from one Observable is emitted during a time window defined according to an item emitted by the other Observable"
- [ ] **merge** [[ReactiveX docs](http://reactivex.io/documentation/operators/merge.html)]: "combine multiple Observables into one by merging their emissions"
- [ ] **start_with** [[ReactiveX docs](http://reactivex.io/documentation/operators/startwith.html)]: "emit a specified sequence of items before beginning to emit the items from the source Observable"
- [ ] **switch** [[ReactiveX docs](http://reactivex.io/documentation/operators/switch.html)]: "convert an Observable that emits Observables into a single Observable that emits the items emitted by the most-recently-emitted of those Observables"
- [ ] **zip** [[ReactiveX docs](http://reactivex.io/documentation/operators/zip.html)]: "combine the emissions of multiple Observables together via a specified function and emit single items for each combination based on the results of this function"
## Error Handling Operators
- [ ] **catch** [[ReactiveX docs](http://reactivex.io/documentation/operators/catch.html)]: "recover from an onError notification by continuing the sequence without error"
- [ ] **retry** [[ReactiveX docs](http://reactivex.io/documentation/operators/retry.html)]: "if a source Observable sends an onError notification, resubscribe to it in the hopes that it will complete without error"
## Observable Utility Operators
- [ ] **delay** [[ReactiveX docs](http://reactivex.io/documentation/operators/delay.html)]: "shift the emissions from an Observable forward in time by a particular amount"
- [ ] **do** [[ReactiveX docs](http://reactivex.io/documentation/operators/do.html)]: "register an action to take upon a variety of Observable lifecycle events"
- [x] **(de-)materialize** [[ReactiveX docs](http://reactivex.io/documentation/operators/materialize-dematerialize.html)]: "represent both the items emitted and the notifications sent as emitted items, or reverse this process"
- [x] **observe_on** [[ReactiveX docs](http://reactivex.io/documentation/operators/observeon.html)]: "specify the scheduler on which an observer will observe this Observable"
- [ ] **serialize** [[ReactiveX docs](http://reactivex.io/documentation/operators/serialize.html)]: "force an Observable to make serialized calls and to be well-behaved"
- [x] **subscribe** [[ReactiveX docs](http://reactivex.io/documentation/operators/subscribe.html)]: "operate upon the emissions and notifications from an Observable"
- [x] **subscribe_on** [[ReactiveX docs](http://reactivex.io/documentation/operators/subscribeon.html)]: "specify the scheduler an Observable should use when it is subscribed to"
- [ ] **time_interval** [[ReactiveX docs](http://reactivex.io/documentation/operators/timeinterval.html)]: "convert an Observable that emits items into one that emits indications of the amount of time elapsed between those emissions"
- [ ] **timeout** [[ReactiveX docs](http://reactivex.io/documentation/operators/timeout.html)]: "mirror the source Observable, but issue an error notification if a particular period of time elapses without any emitted items"
- [ ] **timestamp** [[ReactiveX docs](http://reactivex.io/documentation/operators/timestamp.html)]: "attach a timestamp to each item emitted by an Observable"
- [ ] **using** [[ReactiveX docs](http://reactivex.io/documentation/operators/using.html)]: "create a disposable resource that has the same lifespan as the Observable"
## Conditional and Boolean Operators
- [ ] **all** [[ReactiveX docs](http://reactivex.io/documentation/operators/all.html)]: "determine whether all items emitted by an Observable meet some criteria"
- [ ] **amb** [[ReactiveX docs](http://reactivex.io/documentation/operators/amb.html)]: "given two or more source Observables, emit all of the items from only the first of these Observables to emit an item"
- [ ] **contains** [[ReactiveX docs](http://reactivex.io/documentation/operators/contains.html)]: "determine whether an Observable emits a particular item or not"
- [ ] **default_if_empty** [[ReactiveX docs](http://reactivex.io/documentation/operators/defaultifempty.html)]: "emit items from the source Observable, or a default item if the source Observable emits nothing"
- [ ] **sequence_equal** [[ReactiveX docs](http://reactivex.io/documentation/operators/sequenceequal.html)]: "determine whether two Observables emit the same sequence of items"
- [ ] **skip_until** [[ReactiveX docs](http://reactivex.io/documentation/operators/skipuntil.html)]: "discard items emitted by an Observable until a second Observable emits an item"
- [ ] **skip_while** [[ReactiveX docs](http://reactivex.io/documentation/operators/skipwhile.html)]: "discard items emitted by an Observable until a specified condition becomes false"
- [ ] **take_until** [[ReactiveX docs](http://reactivex.io/documentation/operators/takeuntil.html)]: "discard items emitted by an Observable after a second Observable emits an item or terminates"
- [ ] **take_while** [[ReactiveX docs](http://reactivex.io/documentation/operators/takewhile.html)]: "discard items emitted by an Observable after a specified condition becomes false"
## Mathematical and Aggregate Operators
- [ ] **average** [[ReactiveX docs](http://reactivex.io/documentation/operators/average.html)]: "calculates the average of numbers emitted by an Observable and emits this average"
- [ ] **concat** [[ReactiveX docs](http://reactivex.io/documentation/operators/concat.html)]: "emit the emissions from two or more Observables without interleaving them"
- [ ] **count** [[ReactiveX docs](http://reactivex.io/documentation/operators/count.html)]: "count the number of items emitted by the source Observable and emit only this value"
- [ ] **max** [[ReactiveX docs](http://reactivex.io/documentation/operators/max.html)]: "determine, and emit, the maximum-valued item emitted by an Observable"
- [ ] **min** [[ReactiveX docs](http://reactivex.io/documentation/operators/min.html)]: "determine, and emit, the minimum-valued item emitted by an Observable"
- [ ] **reduce** [[ReactiveX docs](http://reactivex.io/documentation/operators/reduce.html)]: "apply a function to each item emitted by an Observable, sequentially, and emit the final value"
- [ ] **sum** [[ReactiveX docs](http://reactivex.io/documentation/operators/sum.html)]: "calculate the sum of numbers emitted by an Observable and emit this sum"
## Connectable Observable Operators
- [ ] **connect** [[ReactiveX docs](http://reactivex.io/documentation/operators/connect.html)]: "instruct a connectable Observable to begin emitting items to its subscribers"
- [ ] **publish** [[ReactiveX docs](http://reactivex.io/documentation/operators/publish.html)]: "convert an ordinary Observable into a connectable Observable"
- [ ] **ref_count** [[ReactiveX docs](http://reactivex.io/documentation/operators/refcount.html)]: "make a Connectable Observable behave like an ordinary Observable"
- [ ] **replay** [[ReactiveX docs](http://reactivex.io/documentation/operators/replay.html)]: "ensure that all observers see the same sequence of emitted items, even if they subscribe after the Observable has begun emitting items"
## Operators to Convert Observables
- [ ] **to** [[ReactiveX docs](http://reactivex.io/documentation/operators/to.html)]: "convert an Observable into another object or data structure"
## Backpressure Operators for Flows
- [x] **on_backpressure_buffer**: in case of missing backpressure, buffer incoming items up to a specified amount
- [x] **on_backpressure_drop**: in case of missing backpressure, drop incoming items
- [x] **on_backpressure_error**: in case of missing backpressure, issue an error 
- [x] **on_backpressure_latest**: in case of missing backpressure, only keep the latest item
